apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  labels:
    serviceType: php
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: php-fpm
          image: php-fpm # Should be replaced by set image
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/logs
              name: logs
      volumes:
        - name: logs
          emptyDir: {}