commonLabels:
  service: php-fpm

resources:
  - service.yaml
  - deployment.yaml

vars:
  # PHP_FPM_SERVICE_NAME can be used by nginx as value for fastcgi_pass
  - name: PHP_FPM_SERVICE_NAME
    fieldref:
      fieldpath: metadata.name
    objref:
      kind: Service
      name: php-fpm
      apiVersion: v1
