apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      containers:
        - name: nginx:1.19-alpine
          # Command is no longer needed because nginx 1.19 supports env vars
          env:
            # This needs to be dynamic since it varies per environment (acc-app, prod-app, etc.)
            - name: PHP_FPM_SERVICE_NAME
              value: $(PHP_FPM_SERVICE_NAME)
            - name: NGINX_PORT
              value: 80
          # Mount the fastcgi config
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
      volumes:
        - configMap:
            name: nginx-config
          name: nginx-config