apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      containers:
        - name: nginx
          command:
            - /bin/sh
            - -c
            # nginx doesn't support environment variables in its configuration,
            # so we perform the replacement on container start using envsubst.
            - "envsubst '${PHP_FPM_SERVICE_NAME}' < /etc/nginx/conf.d.template/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
          env:
            # This needs to be dynamic since it varies per environment (acc-app, prod-app, etc.)
            - name: PHP_FPM_SERVICE_NAME
              value: $(PHP_FPM_SERVICE_NAME)
          volumeMounts:
            - mountPath: /etc/nginx/conf.d.template
              name: nginx-config-template
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
      volumes:
        - configMap:
            name: nginx-config-template
          name: nginx-config-template