resources:
  - github.com/timfennis/kustomize/nginx

patchesStrategicMerge:
  - deployment.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - config/default.conf

generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous