apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../nginx

patchesStrategicMerge:
  - patches/deployment.yaml

configMapGenerator:
  - name: nginx-config-template
    files:
      - config/default.conf.template

generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
