resources:
  - github.com/timfennis/kustomize/nginx

patchesStrategicMerge:
  - patches/deployment.yaml

configMapGenerator:
  - name: nginx-config-template
    files:
      - config/default.conf.template

generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous