apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: steam
          hostPath:
            path: /var/valheim/steam
        - name: save
          hostPath:
            path: /var/valheim/save
      containers:
        - name: valheim
          image: mbround18/valheim
          ports:
            - containerPort: 32456
              protocol: UDP
            - containerPort: 32457
              protocol: UDP
            - containerPort: 32458
              protocol: UDP
          volumeMounts:
            - mountPath: /home/steam/valheim
              name: steam
            - mountPath: /home/steam/.config/unity3d/IronGate/Valheim
              name: save
      initContainers:
        - name: download-game
          image: busybox
          command:
            - 'sh'
            - '-c'
            - 'wget -O /tmp/save.tar.gz https://s.timfennis.com/dl/valheim.tar.gz; tar --skip-old-files -xvf /tmp/save.tar.gz -C /save'
          volumeMounts:
            - mountPath: /save
              name: save
