apiVersion: v1
kind: Service
metadata:
  name: valheim
spec:
  type: NodePort
  ports:
    - protocol: UDP
      port: 2456
      nodePort: 32456
    - protocol: UDP
      port: 2457
      nodePort: 32457
    - protocol: UDP
      port: 2458
      nodePort: 32458