apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  service: postgres

resources:
  - deployment.yaml
  - service.yaml

vars:
  # POSTGRES_SERVICE_NAME can be used by nginx as value for fastcgi_pass
  - name: POSTGRES_SERVICE_NAME
    fieldref:
      fieldpath: metadata.name
    objref:
      kind: Service
      name: postgres
      apiVersion: v1
